# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Half-Cort and Mid-Raynge
tagline:             'Half-Cort and Mid-Raynge'
description:         'We will let you be in our podcast if you let us be in yours. I said that.'
url:                 http://cschoonover.github.io
baseurl:             'http://cschoonover.github.io'
paginate:            5

# About/contact
author:
  name:              Cortlandt Schoonover
  url:               https://twitter.com/cschoonover
  email:             cmpd.mag@gmail.com

# Custom vars
version:             1.0.0
