# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Avery Lawrence
tagline:             ''
description:         ''
url:                 https://averymlawrence.github.io
baseurl:             'https://averymlawrence.github.io'
paginate:            5

# About/contact
author:
  name:              Avery Lawrence
  url:               
  email:             averymlawrence@gmail.com

# Custom vars
version:             1.0.0

# Misc
licence: 
