# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Half-Cort and Mid-Raynge
tagline:             'Kevin Love, Actually'
description:         'We will let you be in our podcast if you let us be in yours. I said that.'
url:                 https://cschoonover.github.io
baseurl:             'https://cschoonover.github.io'
amazonbaseurl:       http://s3-us-west-2.amazonaws.com/hcmr/
amazonbaseurlhttps:       http://s3-us-west-2.amazonaws.com/hcmr/
paginate:            5

# About/contact
author:
  name:              Cortlandt Schoonover
  url:               https://twitter.com/cschoonover
  email:             cmpd.mag@gmail.com

# Custom vars
version:             1.0.0

# Misc
licence: 
# Podcast
podcast:
  title: Half-Cort and Mid-Raynge
  art: http://cschoonover.github.io/public/infield-in.jpg
  category: 'Sports &amp; Recreation'
  subcategories:
  - Professional
  subtitle: Half-Cort and Mid-Raynge is for and sometimes by Joel
  summary: >
    Half-Cort and Mid-Raynge is for and sometimes by Joel.
    This is a longer summary. Hope it doesn't break the build
